version: '3.9'
services:
  booklog-frontend:
    container_name: booklog-frontend-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - workspace-volume:/workspace/booklog-frontend
      - .:/workspace
volumes:
  workspace-volume: